language: node_js
env:
  global:
    - secure: To10tWcND+7aoBfr+00LZXe1ox5S32pQfGVsw925KUw20FVGg7pB2wCknnMlDXoAgNiazMRTjuAI1uvOb982ayzxUDPgV/EVc/TyxFPKXXE7wUiAkloDXq+EUiOpVOr6TZMJRtPy1Tf+fw/A8gSuTfYDrZCRBuRILuKRQgJ0xZ4IuSgUJSPcG+W2FZv37kNuu/0omxktzCI8SCb2AQDFTVltg73mcKLwKhpRpkDj/L0HhJ1np416NZky26ViJyJp5eltY8+LSysFyDbBmJEigPrSy0yoIGVXwbz7svXtZKQE00WZbV/NDJhe/XNoCZA69UYbpCdPsu5Mm6oLOf4DUpUyx73I1cP7zXtV/MUeLqKHEuV/WKEqbt5X17AcJEhtyclgaZrxeQcvS2TtRrYzn9A+QB4bD5t3QkWiwCqeS9eWrHOvPMtAS8J1o4UXL6Zc0Xbj/w7wgp9m3SFitXoLBCpoTxC2KyGyYxZl+jjQaB2Rt+loCWg7kFvowYp5oMkqlrP9MQHL+wqrYKozAb/5any815ptKdDu+ZtLvQ4EnK5DeF7pkEtWQyUncMg6eBlKM4bCxavKTOiKAdsYUwYeXVJ7jgYc2MA24AmCzrojA7lYk9a4vZpWyblbW13tmz++AY7egTDQxApbat7gRwMIiShjDlu9RpPRvYVh8ZDkMj8=
node_js:
  - lts/erbium
install:
  - npm install
script:
  - set -e
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
