name: ESLint Plugin Backpack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: nvm install
      run: nvm install
    
    - name: Install deps
      run: npm ci

    - name: Run linters
      run: npm run lint

    - name: Test
      run: |
        nvm use
        npm test
